// Copyright 2026 SupraWall Contributors
// SPDX-License-Identifier: Apache-2.0

"use client";

import { useEffect, useState } from "react";
// Removed Supabase import
import { ExternalLink, Search, Layout, AlertCircle } from "lucide-react";

const SITE_DOMAIN = process.env.NEXT_PUBLIC_SITE_DOMAIN || 'https://www.supra-wall.com';

export default function PublishedPages() {
    const [pages, setPages] = useState<any[]>([]);
    const [searchTerm, setSearchTerm] = useState("");
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        fetchPublished();
    }, []);

    async function fetchPublished() {
        setLoading(true);
        setError(null);
        try {
            const res = await fetch('/api/v1/content/published?tenantId=default-tenant');
            if (res.ok) {
                const data = await res.json();
                setPages(data);
            } else {
                setError('Failed to load published pages. Please try again.');
            }
        } catch (e) {
            console.error(e);
            setError('Failed to fetch published pages. Please try again.');
        } finally {
            setLoading(false);
        }
    }

    const filtered = pages.filter(p =>
        p.url?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        p.primary_keyword?.toLowerCase().includes(searchTerm.toLowerCase())
    );

    return (
        <div className="space-y-6">
            <header>
                <h1 className="text-3xl font-bold tracking-tight text-white mb-2">Published Pages</h1>
                <p className="text-neutral-500 text-sm">Monitor all live content generated by your agents.</p>
            </header>

            {error && (
                <div className="flex items-center gap-3 p-4 bg-rose-500/10 border border-rose-500/20 rounded-lg text-rose-400">
                    <AlertCircle className="w-5 h-5 flex-shrink-0" />
                    <p className="text-sm font-medium">{error}</p>
                </div>
            )}

            <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-neutral-500" />
                <input
                    type="text"
                    placeholder="Search by URL or keyword..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="w-full bg-neutral-900 border border-white/5 rounded-xl pl-10 pr-4 py-3 text-sm focus:ring-1 focus:ring-emerald-500 outline-none"
                />
            </div>

            <div className="bg-neutral-900/50 border border-white/5 rounded-2xl overflow-hidden shadow-2xl">
                <table className="w-full text-left border-collapse">
                    <thead>
                        <tr className="border-b border-white/5 text-[10px] font-bold uppercase tracking-widest text-neutral-500 bg-black/20">
                            <th className="px-6 py-4">Page Details</th>
                            <th className="px-6 py-4">Primary Keyword</th>
                            <th className="px-6 py-4">Published Date</th>
                            <th className="px-6 py-4 text-right">View</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-white/5">
                        {loading ? (
                            <tr><td colSpan={4} className="px-6 py-12 text-center text-neutral-500 animate-pulse">Scanning index...</td></tr>
                        ) : filtered.length === 0 ? (
                            <tr><td colSpan={4} className="px-6 py-12 text-center text-neutral-500">No published pages found.</td></tr>
                        ) : (
                            filtered.map(page => (
                                <tr key={page.id} className="hover:bg-white/[0.05] transition-colors group">
                                    <td className="px-6 py-4">
                                        <p className="text-sm font-bold text-white tracking-tight">{page.url}</p>
                                        <p className="text-[10px] text-neutral-500 uppercase font-bold mt-1 tracking-wider">{page.type}</p>
                                    </td>
                                    <td className="px-6 py-4 text-sm text-neutral-400">
                                        {page.primary_keyword}
                                    </td>
                                    <td className="px-6 py-4 text-sm text-neutral-500 tabular-nums">
                                        {new Date(page.published_at).toLocaleDateString()}
                                    </td>
                                    <td className="px-6 py-4 text-right">
                                        <a
                                            href={`${SITE_DOMAIN}${page.url}`}
                                            target="_blank"
                                            className="inline-flex items-center gap-2 text-xs font-bold text-emerald-400 hover:text-emerald-300 transition-colors bg-emerald-500/10 px-3 py-1.5 rounded-lg border border-emerald-500/20"
                                        >
                                            Open <ExternalLink className="w-3 h-3" />
                                        </a>
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>
        </div>
    );
}
