replicaCount: 1

image:
  repository: suprawall/server
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 3000

env:
  databaseUrl: "postgres://postgres:DB_PASSWORD_REDACTED@postgres:5432/suprawall"
  nodeEnv: "production"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
