// Copyright 2026 SupraWall Contributors
// SPDX-License-Identifier: Apache-2.0

// EU AI Act compliance policy templates for high-risk AI deployments.
// Each template is a ready-made rule pack that maps to specific articles.

export interface PolicyTemplateRule {
    toolName: string;
    condition: string;
    ruleType: "DENY" | "REQUIRE_APPROVAL";
    priority: number;
    description: string;
    article: string;
}

export interface PolicyTemplate {
    id: string;
    name: string;
    industry: string;
    tagline: string;
    articles: string[];
    accentClass: string; // Tailwind color variant identifier
    rules: PolicyTemplateRule[];
    // --- EU AI Act Layered Config ---
    baseline: any;
    overrides: any;
}

export const BASELINE_CONFIG = {
    riskManagement: {
        enabled: true,
        registerAutoGenerated: true,
        preDeploymentGate: true,
        reviewIntervalDays: 90,
        anomalyFeedbackLoop: true,
        vulnerableGroupsCheck: true
    },
    dataGovernance: {
        enabled: true,
        dataSourceDeclarationRequired: true,
        relevanceCheck: true,
        biasThresholdAlert: true,
        biasThresholdPercent: 15,
        dataLineageLogging: true
    },
    technicalDocs: {
        enabled: true,
        annexIvWizard: true,
        sectionsRequired: ["description", "design", "training", "performance", "risk", "oversight", "post_market", "conformity"],
        incompleteSectionsBlockDeploy: true,
        versioning: true
    },
    logging: {
        enabled: true,
        retentionMonths: 6,
        immutable: true,
        fields: ["timestamp", "agent_id", "action_type", "input_hash", "output_hash", "confidence", "human_reviewed", "override_by"],
        exportFormats: ["json", "csv", "pdf"]
    },
    transparency: {
        enabled: true,
        outputDisclosureLabel: true,
        disclosureText: "AI-generated output — human verification recommended for consequential decisions",
        deployerInstructionsRequired: true,
        endUserNotice: true
    },
    humanOversight: {
        enabled: true,
        stopButton: true,
        safeHaltState: true,
        approvalGates: [],
        automationBiasAlertThreshold: 5,
        overrideLog: true,
        reviewerIdRequired: true
    },
    accuracyRobustness: {
        enabled: true,
        performanceFloorRequired: true,
        anomalousInputDetection: true,
        fallbackOnLowConfidence: "defer_to_human",
        confidenceThreshold: 0.75
    },
    workflow: {
        qmsEnabled: true,
        conformityAssessmentRequired: true,
        declarationOfConformityGenerated: false,
        ceMarkingStatus: "pending",
        euDatabaseRegistered: false,
        postMarketMonitoringEnabled: true
    }
};

export const POLICY_TEMPLATES: PolicyTemplate[] = [
    {
        id: "eu-ai-act-hr",
        name: "HR & Employment",
        industry: "Human Resources",
        tagline: "Safeguards for AI in hiring, performance reviews, and employment decisions.",
        articles: ["Art. 9", "Art. 14", "Art. 13"],
        accentClass: "violet",
        baseline: BASELINE_CONFIG,
        overrides: {
            hireFireBlock: true,
            outputTypeMax: "recommendation",
            biasAuditTrail: true,
            biasThresholdPercent: 15,
            employeeNotificationGate: true,
            dpiaRequired: true,
            dataMinimizationEnforcement: true,
            explainabilityRequired: true,
            logRetentionMonths: 6,
        },
        rules: [
            {
                toolName: "*",
                condition: "(hire|reject|shortlist).*(candidate|applicant|employee)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 10,
                description: "Hiring and rejection decisions require human sign-off",
                article: "Art. 14",
            },
            {
                toolName: "*",
                condition: "(terminate|dismiss|layoff|fire|redundanc)",
                ruleType: "DENY",
                priority: 1,
                description: "Automated employee termination is blocked — requires human authority",
                article: "Art. 9",
            },
            {
                toolName: "*",
                condition: "(salary|compensation|bonus|pay.?rise|pay.?increase)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 15,
                description: "Compensation changes require HR manager approval",
                article: "Art. 14",
            },
            {
                toolName: "*",
                condition: "(performance.review|appraisal|evaluation).*(submit|publish|final)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 20,
                description: "Performance evaluations must be reviewed before publishing",
                article: "Art. 14",
            },
            {
                toolName: "database",
                condition: "bulk.*(export|download).*(employ|staff|personnel|hr)",
                ruleType: "DENY",
                priority: 5,
                description: "Prevent bulk export of HR and employee personal data",
                article: "Art. 10",
            },
        ],
    },
    {
        id: "eu-ai-act-healthcare",
        name: "Healthcare",
        industry: "Medical & Clinical",
        tagline: "Guardrails for AI in medical diagnosis, patient records, and clinical decisions.",
        articles: ["Art. 9", "Art. 14", "Art. 10"],
        accentClass: "rose",
        baseline: BASELINE_CONFIG,
        overrides: {
            phiHandling: {
                encryptionInTransit: true,
                encryptionAtRest: true,
                accessLogging: true,
                breachNotificationWorkflow: true
            },
            clinicalOutputDisclaimer: "This AI output does not constitute medical advice.",
            logRetentionMonths: 36,
        },
        rules: [
            {
                toolName: "*",
                condition: "(patient|ehr|medical.record|health.record).*(write|update|modify|create)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 10,
                description: "Medical record modifications require clinician approval",
                article: "Art. 14",
            },
            {
                toolName: "database",
                condition: "DELETE.*(patient|health|clinical|medical)",
                ruleType: "DENY",
                priority: 1,
                description: "Block deletion of patient health records",
                article: "Art. 9",
            },
            {
                toolName: "*",
                condition: "(dosage|prescription|medic[ai]tion|drug.order)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 5,
                description: "Medication and prescription actions require physician sign-off",
                article: "Art. 14",
            },
            {
                toolName: "*",
                condition: "(send|share|transmit|export).*patient",
                ruleType: "DENY",
                priority: 3,
                description: "Block unauthorised sharing of patient data outside the system",
                article: "Art. 10",
            },
            {
                toolName: "*",
                condition: "(diagnos[ei]|treatment.plan|clinical.decision)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 15,
                description: "Clinical decisions must be reviewed by a qualified professional",
                article: "Art. 14",
            },
        ],
    },
    {
        id: "eu-ai-act-education",
        name: "Education",
        industry: "Education & Training",
        tagline: "AI safeguards for admissions, student evaluation, and learning management systems.",
        articles: ["Art. 9", "Art. 14", "Art. 10"],
        accentClass: "amber",
        baseline: BASELINE_CONFIG,
        overrides: {
            admissionDenialGate: true,
            explainabilityRequired: true,
            examFlagReviewGate: true,
            profilingAllowedAttributes: ["academic_performance", "attendance"],
            vulnerableGroupExtraReview: true,
            appealNoticeAutoAppend: true,
        },
        rules: [
            {
                toolName: "*",
                condition: "(admit|reject|admission|enrollment).*(student|applicant)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 10,
                description: "Educational admission decisions require human oversight",
                article: "Art. 14",
            },
            {
                toolName: "*",
                condition: "(grade|score|marking|evaluation).*(exam|assignment|student)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 15,
                description: "AI-generated grades must be reviewed by an educator",
                article: "Art. 14",
            },
            {
                toolName: "browser",
                condition: "(proctor|monitor|eye-tracking|cheat-detection)",
                ruleType: "DENY",
                priority: 1,
                description: "Block invasive AI-powered student monitoring activities",
                article: "Art. 9",
            },
            {
                toolName: "*",
                condition: "behavioral.*(profile|score|ranking)",
                ruleType: "DENY",
                priority: 5,
                description: "Prevent behavioral profiling of students for disciplinary actions",
                article: "Art. 10",
            },
        ],
    },
    {
        id: "eu-ai-act-infrastructure",
        name: "Critical Infrastructure",
        industry: "Utilities & Energy",
        tagline: "Security controls for AI-driven management of water, gas, electricity, and heating.",
        articles: ["Art. 9", "Art. 14", "Art. 12"],
        accentClass: "emerald",
        baseline: BASELINE_CONFIG,
        overrides: {
            failsafeKillSwitch: true,
            physicalActionGate: true,
            loggingMode: "continuous_stream",
            disconnectionSafetyModeRequired: true,
            cascadeRiskThreshold: 1000,
            anomalyAutoHalt: true,
        },
        rules: [
            {
                toolName: "system",
                condition: "(shutdown|reboot|restart|stop).*(grid|plant|node|reactor)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 1,
                description: "Infrastructure shutdown operations require senior engineer authorization",
                article: "Art. 14",
            },
            {
                toolName: "config",
                condition: "(threshold|limit|capacity|load-balance)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 10,
                description: "Changes to critical operational limits require human validation",
                article: "Art. 14",
            },
            {
                toolName: "logs",
                condition: "(delete|purge|wipe|clear).*(safety|security|audit)",
                ruleType: "DENY",
                priority: 1,
                description: "Block deletion of safety and security logs for infrastructure",
                article: "Art. 12",
            },
            {
                toolName: "network",
                condition: "(route|gateway|firewall).*(disable|bypass|open)",
                ruleType: "DENY",
                priority: 5,
                description: "Prevent AI from bypassing critical network security layers",
                article: "Art. 9",
            },
        ],
    },
    {
        id: "eu-ai-act-biometrics",
        name: "Biometrics",
        industry: "Biometric Systems",
        tagline: "High-stakes controls for identification, categorization, and emotion recognition.",
        articles: ["Art. 9", "Art. 14", "Art. 5"],
        accentClass: "indigo",
        baseline: BASELINE_CONFIG,
        overrides: {
            realtimePublicIdBlock: true,
            emotionRecognitionScope: ["workplace_safety", "medical"],
            inferenceBlock: ["ethnicity", "religion", "political_opinion"],
            twoPersonVerification: true,
            perIdentificationLogging: true,
            conformityAssessmentType: "third_party_locked",
            logRetentionMonths: 24,
        },
        rules: [
            {
                toolName: "camera",
                condition: "(identify|match|recognize).*(biometric|face|iris|fingerprint)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 1,
                description: "Real-time biometric identification requires strict human oversight",
                article: "Art. 14",
            },
            {
                toolName: "*",
                condition: "(emotion|mood|sentiment).*(detect|analyze|classify)",
                ruleType: "DENY",
                priority: 1,
                description: "Block AI-powered emotion recognition in workplace or education",
                article: "Art. 5",
            },
            {
                toolName: "database",
                condition: "(categorize|tag|label).*(race|religion|sexual|political)",
                ruleType: "DENY",
                priority: 1,
                description: "Ban on biometric categorization based on sensitive characteristics",
                article: "Art. 5",
            },
            {
                toolName: "*",
                condition: "(enroll|register|store).*(biometric|faceprint)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 10,
                description: "Adding new biometric signatures requires manual confirmation",
                article: "Art. 14",
            },
        ],
    },
    {
        id: "eu-ai-act-police",
        name: "Law Enforcement",
        industry: "Public Safety",
        tagline: "Rigorous controls for risk assessment, polygraphs, and criminal profiling.",
        articles: ["Art. 9", "Art. 14", "Art. 10"],
        accentClass: "blue",
        baseline: BASELINE_CONFIG,
        overrides: {
            profilingOutputFlag: true,
            probabilisticLabelEnforced: true,
            actionFromProfileAloneBlock: true,
            soleAutomationBlock: true,
            sensitiveCategoryInputBlock: ["race", "ethnicity", "religion"],
            twoPersonVerification: true,
            conformityAssessmentType: "third_party_locked",
            logRetentionMonths: 36,
        },
        rules: [
            {
                toolName: "*",
                condition: "(predict|score|probability).*(recidivism|crime|offense|guilt)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 1,
                description: "Criminal risk assessments must be reviewed by legal authorities",
                article: "Art. 14",
            },
            {
                toolName: "media",
                condition: "(deepfake|synthetic|manipulated).*(confidence|detect|label)",
                ruleType: "DENY",
                priority: 5,
                description: "Block AI from suppressing deepfake detection warnings",
                article: "Art. 10",
            },
            {
                toolName: "database",
                condition: "(search|query|lookup).*(interpol|fbi|police|criminal).*(citizen|person)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 10,
                description: "Law enforcement database lookups require probable cause logging",
                article: "Art. 14",
            },
            {
                toolName: "*",
                condition: "(polygraph|lie-detector|stress-analysis)",
                ruleType: "DENY",
                priority: 1,
                description: "Restrict AI use in lie detection and physiological stress analysis",
                article: "Art. 9",
            },
        ],
    },
    {
        id: "eu-ai-act-migration",
        name: "Migration & Border Control",
        industry: "Migration & Asylum",
        tagline: "Safeguards for visa processing, travel document verification, and asylum analysis.",
        articles: ["Art. 9", "Art. 14", "Art. 13"],
        accentClass: "cyan",
        baseline: BASELINE_CONFIG,
        overrides: {
            autonomousAsylumVisaBlock: true,
            outputTypeMax: "supporting_information",
            allRiskScoresReviewGate: true,
            antiDiscriminationAuditGate: true,
            scoringBlockedAttributes: ["nationality", "ethnicity", "religion"],
            vulnerablePersonEscalation: true,
            twoPersonVerification: true,
            conformityAssessmentType: "third_party_locked",
            logRetentionMonths: 36,
        },
        rules: [
            {
                toolName: "visa",
                condition: "(approve|reject|grant|deny).*(visa|asylum|entry)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 1,
                description: "Asylum and visa decisions require human immigration officer review",
                article: "Art. 14",
            },
            {
                toolName: "scanner",
                condition: "(valid|invalid|forged|authentic).*(passport|id|document)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 10,
                description: "Automated document verification must provide explainability for rejections",
                article: "Art. 13",
            },
            {
                toolName: "*",
                condition: "(risk-score|security-level).*(traveler|migrant|refugee)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 5,
                description: "Security profiling of migrants requires manual oversight",
                article: "Art. 14",
            },
            {
                toolName: "system",
                condition: "(bypass|override|skip).*(identity-check|biometric-verify)",
                ruleType: "DENY",
                priority: 1,
                description: "Block AI from bypassing mandatory identity verification protocols",
                article: "Art. 9",
            },
        ],
    },
    {
        id: "eu-ai-act-justice",
        name: "Justice & Democracy",
        industry: "Legal & Judicial",
        tagline: "Specialized controls for legal research, judicial interpretation, and democratic processes.",
        articles: ["Art. 9", "Art. 14", "Art. 11"],
        accentClass: "fuchsia",
        baseline: BASELINE_CONFIG,
        overrides: {
            nonBindingLabelEnforced: true,
            sentencingRecommendationBlock: true,
            electoralInfluenceDisabled: true,
            legalOutcomeScope: ["case_law_summary", "precedent_research"],
            judicialReviewGate: true,
            conformityAssessmentType: "third_party_locked",
            logRetentionMonths: 60,
        },
        rules: [
            {
                toolName: "legal",
                condition: "(interpret|apply|rule).*(statute|precedent|law)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 1,
                description: "AI-assisted judicial interpretation requires judge approval",
                article: "Art. 14",
            },
            {
                toolName: "*",
                condition: "(predict|forecast).*(sentence|outcome|verdict|judgement)",
                ruleType: "DENY",
                priority: 1,
                description: "Ban on automated predictive sentencing and verdict forecasting",
                article: "Art. 9",
            },
            {
                toolName: "social",
                condition: "(influence|manipulate|target).*(voter|election|ballot)",
                ruleType: "DENY",
                priority: 1,
                description: "Strict prohibition on election manipulation and voter targeting",
                article: "Art. 11",
            },
            {
                toolName: "database",
                condition: "(export|analyze).*(voter|party-affiliation|political-leaning)",
                ruleType: "REQUIRE_APPROVAL",
                priority: 10,
                description: "Processing of political affiliation data requires democratic oversight",
                article: "Art. 14",
            },
        ],
    },
];
